SELECT 
    SUBSTRING(CONVERT(VARCHAR, GIN_DATE), 5, 2) AS Month,
    ROUND(SUM(Inv_Value), 0) AS Purchases
FROM PurMastTable
WHERE GIN_DATE BETWEEN 20210401 AND 20220331
GROUP BY
    SUBSTRING(CONVERT(VARCHAR, GIN_DATE), 1, 4),
    SUBSTRING(CONVERT(VARCHAR, GIN_DATE), 5, 2)
ORDER BY
    SUBSTRING(CONVERT(VARCHAR, GIN_DATE), 1, 4),
    SUBSTRING(CONVERT(VARCHAR, GIN_DATE), 5, 2) DESC