SELECT 
    SUBSTRING(CONVERT(VARCHAR, BILL_DATE), 5, 2) AS Month,
    ROUND(SUM(BILL_AMT), 0) AS Sales
FROM billmasttable
WHERE Bill_Date BETWEEN 20210401 AND 20220331
GROUP BY SUBSTRING(CONVERT(VARCHAR, BILL_DATE), 5, 2)
ORDER BY SUBSTRING(CONVERT(VARCHAR, BILL_DATE), 5, 2) DESC